### ISSUE TITLE
Do you have script that export xml file with tags and images?

### ISSUE THREAD

**Issue by lucasmmduran** [GitBruno/Novelty#2]
Hi, do you have script that export xml file with tags and images jpg? Thank you

**Comment by GitBruno** [comment]
To export XML we can simply  export as IDML. (IDML is an XML package) I don’t have a script for this but you could easily automate this. 

Package the native file ticking the `Copy Linked Graphics`, `Update Graphic Links In Package` and `Include IDML` tickbox.

Then to work with the XML files within unzip IDML file:

    unzip docname.idml -d docname

**Comment by GitBruno** [comment]
Feel free to contribute this script here if you make it!
